#= require jquery
#= require jquery_ujs
#= require turbolinks
#= require handlebars
#= require ember
#= require ember-data
#= require_self
#= require unoriginal_raffler
UnoriginalRaffler = Ember.Application.create()
